# Generated by Django 2.2.17 on 2021-02-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20210209_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя врача')),
                ('last_name', models.CharField(max_length=50, verbose_name='фамилия врача')),
                ('phone', models.CharField(max_length=50, verbose_name='номер телефона')),
            ],
        ),
    ]
